version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "test-name"
s3_bucket = "rust-lambdas-test"
s3_prefix = "test-name"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
