version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "holdcrypt"
s3_bucket = "holdcrypt"
s3_prefix = "lambdas"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
