AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

## These settings are used for every lambda and API
Globals:
  Function:
    CodeUri: target/lambda/
    Runtime: provided.al2
    Handler: bootstrap
    Architectures: ["x86_64"]
    Timeout: 30
    MemorySize: 128
    # Environment:
    #   Variables:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
    Auth:
      AddDefaultAuthorizerToCorsPreflight: False

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda/hello
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /v1/hello
            Method: GET
  HelloNameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda/hello_name
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /v1/hello_name
            Method: GET
  AddUser:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda/add_user
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /v1/user
            Method: POST
  AddTransaction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda/add_transaction
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /v1/user/{username}/transaction
            Method: POST
  Closure:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda/closure
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /v1/closure
            Method: POST
  CustomResponse:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/lambda/custom_response
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /v1/custom_response
            Method: POST
Outputs:
  HelloWorldName:
    Value: !Ref HelloWorldFunction
    Description: Name of the Lambda function
  # HelloName:
  #   Value: !Ref HelloNameFunction
  #   Description: Name of the Lambda function

